export default {
  language: 'தமிழ்',
  newTree: 'புதிய மரம்',
  downloadTreeData: 'மர விவரங்களை பதிவிறக்கு',
  saveFamilyTree: 'குடும்ப மரத்தை சேமிக்கவும்',
  saving: 'சேமிக்கிறது...',
  total: 'மொத்தம்',
  males: 'ஆண்கள்',
  females: 'பெண்கள்',
  generations: 'தலைமுறைகள்',
  familyTreeSaved: 'குடும்ப மரம் வெற்றிகரமாக சேமிக்கப்பட்டது!',
  failedToSave: 'குடும்ப மரத்தை சேமிக்க முடியவில்லை.',
  cannotDeleteRoot: 'ரூட் நபரை நீக்க முடியாது.',
  confirmDelete: 'இந்த நபரையும் அவர்களின் அனைத்து இணைப்புகளையும் நீக்க விரும்புகிறீர்களா? இதை மீளமைக்க முடியாது.',
  confirmNewTree: 'புதிய மரத்தைத் தொடங்க விரும்புகிறீர்களா? அனைத்து தற்போதைய தரவும் இழக்கப்படும்.',
  relationships: {
    father: 'அப்பா',
    mother: 'அம்மா',
    son: 'மகன்',
    daughter: 'மகள்',
    brother: 'சகோதரன்',
    sister: 'சகோதரி',
    husband: 'கணவன்',
    wife: 'மனைவி',
    grandfather: 'தாத்தா',
    grandmother: 'பாட்டி',
    grandson: 'பேரன்',
    granddaughter: 'பேத்தி',
    uncle: 'மாமா',
    aunt: 'அத்தை',
    nephew: 'மருமகன்',
    niece: 'மருமகள்',
    cousin: 'சகோதரி/சகோதரன்',
    fatherInLaw: 'மாமனார்',
    motherInLaw: 'மாமியார்',
    sonInLaw: 'மருமகன்',
    daughterInLaw: 'மருமகள்',
    brotherInLaw: 'மைத்துனன்',
    sisterInLaw: 'மைத்துனி',
    stepFather: 'மாற்றாந்தந்தை',
    stepMother: 'மாற்றாந்தாய்',
    stepSon: 'மாற்றாந்தனயன்',
    stepDaughter: 'மாற்றாந்தனயி',
    stepBrother: 'மாற்றாந்தம்பி',
    stepSister: 'மாற்றாந்தங்கை',
    greatGrandfather: 'முப்பாட்டன்',
    greatGrandmother: 'முப்பாட்டி',
    greatGrandson: 'முப்பேரன்',
    greatGranddaughter: 'முப்பேத்தி',
    relative: 'உறவினர்',
    familyMember: 'குடும்ப உறுப்பினர்',
    ancestor: 'முன்னோர்',
    descendant: 'பரம்பரை',
    relationshipTo: 'உறவு',
    isMy: 'எனக்கு',
    of: 'இன்',
    sameGeneration: 'ஒரே தலைமுறை',
    olderGeneration: 'மூத்த தலைமுறை',
    youngerGeneration: 'இளைய தலைமுறை',
    generationGap: 'தலைமுறை இடைவெளி',
    self: 'நானே',
    unknown: 'தெரியாது',
    deceased: 'இறந்தவர்',
    adopted: 'தத்தெடுக்கப்பட்ட',
    foster: 'வளர்ப்பு',
  },
  addParents: 'பெற்றோர்களை சேர்க்கவும்',
  addSpouse: 'துணையை சேர்க்கவும்',
  addChild: 'குழந்தையை சேர்க்கவும்',
  addSibling: 'சகோதரரை சேர்க்கவும்',
  edit: 'திருத்து',
  delete: 'நீக்கு',
  name: 'பெயர்',
  gender: 'பாலினம்',
  age: 'வயது',
  male: 'ஆண்',
  female: 'பெண்',
  selectExistingMember: 'இருக்கும் உறுப்பினரைத் தேர்ந்தெடுக்கவும்',
  addNewMember: 'புதிய உறுப்பினரைச் சேர்க்கவும்',
  selectPersonToSeeRelationship: 'உறவைக் காண நபரைத் தேர்ந்தெடுக்கவும்',
  noRelationshipFound: 'உறவு கண்டுபிடிக்கப்படவில்லை',
  relationshipCalculated: 'உறவு கணக்கிடப்பட்டது',
}; 