// English Relationship Mapping - Universal, Gender-Aware
const englishRelationships = {
  "F": "Father",
  "M": "Mother",
  "H": "Husband",
  "elder sister": "Elder Sister",
  "younger sister": "Younger Sister",
  "Z+H": "Elder Sister's Husband",
  "Z-H": "Younger Sister's Husband",
  "younger brother": "Younger Brother",
  "B-W": "Younger Brother's Wife",
  "daughter": "Daughter",
  "son": "Son",
  "B-S": "Younger Brother's Son",
  "B-D": "Younger Brother's Daughter",
  "B+S": "Elder Brother's Son",
  "B+D": "Elder Brother's Daughter",
  "Z+S": "Elder Sister's Son",
  "Z+D": "Elder Sister's Daughter",
  "Z-S": "Younger Sister's Son",
  "Z-D": "Younger Sister's Daughter",
  "SW": "Son's Wife",
  "DH": "Daughter's Husband",
  "grandson": "Grandson",
  "granddaughter": "Granddaughter",
  "grandmother (paternal)": "Paternal Grandmother",
  "grandfather (paternal)": "Paternal Grandfather",
  "HFM": "Husband's Father's Mother",
  "HFF": "Husband's Father's Father",
  "grandmother (maternal)": "Maternal Grandmother",
  "grandfather (maternal)": "Maternal Grandfather",
  "mother's younger brother": "Mother's Younger Brother",
  "MB-W": "Mother's Younger Brother's Wife",
  "mother's younger sister": "Mother's Younger Sister",
  "MZ-H": "Mother's Younger Sister's Husband",
  "MB-S": "Mother's Younger Brother's Son",
  "MB-SW": "Mother's Younger Brother's Son's Wife",
  "FFM": "Father's Father's Mother",
  "FFF": "Father's Father's Father",
  "FFB+W": "Father's Father's Elder Brother's Wife",
  "FFB+": "Father's Father's Elder Brother",
  "FFB+S": "Father's Father's Elder Brother's Son",
  "FFB+SW": "Father's Father's Elder Brother's Son's Wife",
  "FFB+DH": "Father's Father's Elder Brother's Daughter's Husband",
  "FFB+D": "Father's Father's Elder Brother's Daughter",
  "FZ+H": "Father's Sister's Husband",
  "father's elder sister": "Father's Elder Sister",
  "FB+W": "Father's Elder Brother's Wife",
  "father's elder brother": "Father's Elder Brother",
  "HFB-W": "Husband's Father's Younger Brother's Wife",
  "HFB-": "Husband's Father's Younger Brother",
  "HFZ+H": "Husband's Father's Elder Sister's Husband",
  "HFZ+": "Husband's Father's Elder Sister",
  "HM": "Husband's Mother",
  "HF": "Husband's Father",
  "HFZ-H": "Husband's Father's Younger Sister's Husband",
  "HFZ-": "Husband's Father's Younger Sister",
  "FFB+DD": "Father's Father's Elder Brother's Daughter's Daughter",
  "FFB+DDH": "Father's Father's Elder Brother's Daughter's Daughter's Husband",
  "FZ+D": "Father's Sister's Daughter",
  "FZ+SW": "Father's Sister's Son's Wife",
  "FZ+S": "Father's Sister's Son",
  "MB-S": "Mother's Younger Brother's Son",
  "FB+S": "Father's Elder Brother's Son",
  "FB+SW": "Father's Elder Brother's Son's Wife",
  "HFB-SW": "Husband's Father's Younger Brother's Son's Wife",
  "HFB-S": "Husband's Father's Younger Brother's Son",
  "HFB-DH": "Husband's Father's Younger Brother's Daughter's Husband",
  "HFB-D": "Husband's Father's Younger Brother's Daughter",
  "HZ-H": "Husband's Sister's Husband",
  "HZ-": "Husband's Sister",
  "HFZ+S": "Husband's Father's Elder Sister's Son",
  "HFZ-DH": "Husband's Father's Younger Sister's Daughter's Husband",
  "HFZ-D": "Husband's Father's Younger Sister's Daughter",
  "FZ+DD": "Father's Sister's Daughter's Daughter",
  "FZ+DDH": "Father's Sister's Daughter's Daughter's Husband",
  "FZ+SD": "Father's Sister's Son's Daughter",
  "FZ+SS": "Father's Sister's Son's Son",
  "FZ+DSW": "Father's Sister's Daughter's Son's Wife",
  "FZ+DS": "Father's Sister's Daughter's Son",
  "MB-SS": "Mother's Younger Brother's Son's Son",
  "MB-SD": "Mother's Younger Brother's Son's Daughter",
  "FB+SSW": "Father's Elder Brother's Son's Son's Wife",
  "FB+SS": "Father's Elder Brother's Son's Son",
  "HZ-S": "Husband's Sister's Son",
  "HFB-SD": "Husband's Father's Younger Brother's Son's Daughter",
  "HFB-SS": "Husband's Father's Younger Brother's Son's Son",
  "HFB-DD": "Husband's Father's Younger Brother's Daughter's Daughter",
  "HFB-DS": "Husband's Father's Younger Brother's Daughter's Son",
  "HFZ-DS": "Husband's Father's Younger Sister's Daughter's Son",
  "HFZ-DD": "Husband's Father's Younger Sister's Daughter's Daughter",
  "FB+SDH": "Father's Elder Brother's Son's Daughter's Husband",
  "FB+SD": "Father's Elder Brother's Son's Daughter",
  "HZ-DH": "Husband's Sister's Daughter's Husband",
  "HZ-D": "Husband's Sister's Daughter",
  "FZ+DDS": "Father's Sister's Daughter's Daughter's Son",
  "FZ+DSD": "Father's Sister's Daughter's Son's Daughter",
  "FZ+DSDH": "Father's Sister's Daughter's Son's Daughter's Husband",
  "FB+SSS": "Father's Elder Brother's Son's Son's Son",
  "FB+SSD": "Father's Elder Brother's Son's Son's Daughter",
  "FB+SDD": "Father's Elder Brother's Son's Daughter's Daughter",
  "HZ-DS": "Husband's Sister's Daughter's Son",
  "HZ-DD": "Husband's Sister's Daughter's Daughter"
};

export default englishRelationships; 