// English Relationship Mapping - Universal, Gender-Aware
// Usage: englishRelationships[code] where code is a universal relationship code (e.g., FB+S)
// Covers direct, sibling, in-law, uncle/aunt, cousin, grandparent, great-grandparent, and step relationships

const englishRelationships = {
  F: "Father",
  M: "Mother",
  H: "Husband",
  "FZ+": "Father's elder sister",
  "Z-": "Younger sister",
  "Z+H": "Elder sister's husband",
  "Z-H": "Younger sister's husband",
  "B-": "Younger brother",
  "B-W": "Younger brother's wife",
  D: "Daughter",
  S: "Son",
  "B-S": "Younger brother's son",
  "B-D": "Younger brother's daughter",
  "B+S": "Elder brother's son",
  "B+D": "Elder brother's daughter",
  "Z+S": "Elder sister's son",
  "Z+D": "Elder sister's daughter",
  "Z-S": "Younger sister's son",
  "Z-D": "Younger sister's daughter",
  SW: "Daughter-in-law",
  DH: "Son-in-law",
  grandson: "Grandson",
  granddaughter: "Granddaughter",
  FM: "Paternal grandmother",
  FF: "Paternal grandfather",
  HFM: "Husband's father's mother",
  HFF: "Husband's father's father",
  MM: "Maternal grandmother",
  MF: "Maternal grandfather",
  "MB-": "Mother's younger brother",
  "MB-W": "Mother's younger brother's wife",
  "MZ-": "Mother's younger sister",
  "MZ-H": "Mother's younger sister's husband",
  "MB-S": "Mother's younger brother's son",
  "MB-SW": "Mother's younger brother's son's wife",
  FFM: "Father's father's mother",
  FFF: "Father's father's father",
  "FFB+W": "Father's father's elder brother's wife",
  "FFB+": "Father's father's elder brother",
  "FFB+S": "Father's father's elder brother's son",
  "FFB+SW": "Father's father's elder brother's son's wife",
  "FFB+DH": "Father's father's elder brother's daughter's husband",
  "FFB+D": "Father's father's elder brother's daughter",
  "FZ+H": "Father's sister's husband",
  "father's elder sister": "Father's elder sister",
  "FB+W": "Father's elder brother's wife",
  "father's elder brother": "Father's elder brother",
  "HFB-W": "Husband's father's younger brother's wife",
  "HFB-": "Husband's father's younger brother",
  "HFZ+H": "Husband's father's elder sister's husband",
  "HFZ+": "Husband's father's elder sister",
  HM: "Husband's mother",
  HF: "Husband's father",
  "HFZ-H": "Husband's father's younger sister's husband",
  "HFZ-": "Husband's father's younger sister",
  "FFB+DD": "Father's father's elder brother's daughter's daughter",
  "FFB+DDH": "Father's father's elder brother's daughter's daughter's husband",
  "FZ+D": "Father's sister's daughter",
  "FZ+SW": "Father's sister's son's wife",
  "FZ+S": "Father's sister's son",
  "MB-S": "Mother's younger brother's son",
  "FB+S": "Father's elder brother's son",
  "FB+SW": "Father's elder brother's son's wife",
  "HFB-SW": "Husband's father's younger brother's son's wife",
  "HFB-S": "Husband's father's younger brother's son",
  "HFB-DH": "Husband's father's younger brother's daughter's husband",
  "HFB-D": "Husband's father's younger brother's daughter",
  "HZ-H": "Husband's sister's husband",
  "HZ-": "Husband's sister",
  "HFZ+S": "Husband's father's elder sister's son",
  "HFZ-DH": "Husband's father's younger sister's daughter's husband",
  "HFZ-D": "Husband's father's younger sister's daughter",
  "FZ+DD": "Father's sister's daughter's daughter",
  "FZ+DDH": "Father's sister's daughter's daughter's husband",
  "FZ+SD": "Father's sister's son's daughter",
  "FZ+SS": "Father's sister's son's son",
  "FZ+DSW": "Father's sister's daughter's son's wife",
  "FZ+DS": "Father's sister's daughter's son",
  "MB-SS": "Mother's younger brother's son's son",
  "MB-SD": "Mother's younger brother's son's daughter",
  "FB+SSW": "Father's elder brother's son's son's wife",
  "FB+SS": "Father's elder brother's son's son",
  "HZ-S": "Husband's sister's son",
  "HFB-SD": "Husband's father's younger brother's son's daughter",
  "HFB-SS": "Husband's father's younger brother's son's son",
  "HFB-DD": "Husband's father's younger brother's daughter's daughter",
  "HFB-DS": "Husband's father's younger brother's daughter's son",
  "HFZ-DS": "Husband's father's younger sister's daughter's son",
  "HFZ-DD": "Husband's father's younger sister's daughter's daughter",
  "FB+SDH": "Father's elder brother's son's daughter's husband",
  "FB+SD": "Father's elder brother's son's daughter",
  "HZ-DH": "Husband's sister's daughter's husband",
  "HZ-D": "Husband's sister's daughter",
  "FZ+DDS": "Father's sister's daughter's daughter's son",
  "FZ+DSD": "Father's sister's daughter's son's daughter",
  "FZ+DSDH": "Father's sister's daughter's son's daughter's husband",
  "FB+SSS": "Father's elder brother's son's son's son",
  "FB+SSD": "Father's elder brother's son's son's daughter",
  "FB+SDD": "Father's elder brother's son's daughter's daughter",
  "HZ-DS": "Husband's sister's daughter's son",
  "HZ-DD": "Husband's sister's daughter's daughter",
  "FB+SDS": "Father's elder brother's son's daughter's son",
  "FB+SDSD": "Father's elder brother's son's daughter's son's daughter",
  WF: "Wife's father (father-in-law)",
  WM: "Wife's mother (mother-in-law)",
  "WB+": "Wife's elder brother",
  "WB-": "Wife's younger brother",
  "WZ+": "Wife's elder sister",
  "WZ-": "Wife's younger sister",
  "WB+W": "Wife's elder brother's wife",
  "WB-W": "Wife's younger brother's wife",
  "WZ+H": "Wife's elder sister's husband",
  "WZ-H": "Wife's younger sister's husband",
  "WB+S": "Wife's elder brother's son",
  "WB+D": "Wife's elder brother's daughter",
  "WB-S": "Wife's younger brother's son",
  "WB-D": "Wife's younger brother's daughter",
  "WZ+S": "Wife's elder sister's son",
  "WZ+D": "Wife's elder sister's daughter",
  "WZ-S": "Wife's younger sister's son",
  "WZ-D": "Wife's younger sister's daughter",
  WFF: "Wife's father's father",
  WFM: "Wife's father's mother",
  WMF: "Wife's mother's father",
  WMM: "Wife's mother's mother",
  "WFB+": "Wife's father's elder brother",
  "WFB-": "Wife's father's younger brother",
  "WFZ+": "Wife's father's elder sister",
  "WFZ-": "Wife's father's younger sister",
  "WMB+": "Wife's mother's elder brother",
  "WMB-": "Wife's mother's younger brother",
  "WMZ+": "Wife's mother's elder sister",
  "WMZ-": "Wife's mother's younger sister",
  "WFB+W": "Wife's father's elder brother's wife",
  "WFB-W": "Wife's father's younger brother's wife",
  "WFZ+H": "Wife's father's elder sister's husband",
  "WFZ-H": "Wife's father's younger sister's husband",
  "WMB+W": "Wife's mother's elder brother's wife",
  "WMB-W": "Wife's mother's younger brother's wife",
  "WMZ+H": "Wife's mother's elder sister's husband",
  "WMZ-H": "Wife's mother's younger sister's husband",
  "FB+": "Father's elder brother",
  "FZ+": "Father's elder sister",
  "SS": "Grandson",
  "DD": "Granddaughter",
  "DS": "Grandson",
  "SD": "Granddaughter",
  "FZ+DH": "Father's elder sister's daughter's husband",
  // UI Text Translations
  "associatedFamilyTreesForUser": "Associated Family Trees for User",
  "associatedFamilyTree": "Associated Family Tree",
  "showingAllFamilyTrees": "Showing all family trees connected to this user through relationships and associations.",
  "back": "Back",
  "myBirthFamilyTree": "My Birth Family Tree",
  "noMembersFound": "No members found in this associated family tree.",
  "couldNotLoadTree": "Could not load associated family tree.",
  "loadingAssociatedFamilyTree": "Loading associated family tree...",
  "connectedFamilyTrees": "Connected Family Trees",
  "totalCrossFamilyConnections": "Total cross-family connections"
};

export default englishRelationships;