export default {
  language: 'English',
  newTree: 'New Tree',
  downloadTreeData: 'Download Tree Data',
  saveFamilyTree: 'Save Family Tree',
  saving: 'Saving...',
  total: 'Total',
  males: 'Males',
  females: 'Females',
  generations: 'Generations',
  familyTreeSaved: 'Family tree saved successfully!',
  failedToSave: 'Failed to save family tree.',
  cannotDeleteRoot: 'Cannot delete the root person.',
  confirmDelete: 'Are you sure you want to delete this person and all their connections? This cannot be undone.',
  confirmNewTree: 'Are you sure you want to start a new tree? All current data will be lost.',
  relationships: {
    father: 'Father',
    mother: 'Mother',
    son: 'Son',
    daughter: 'Daughter',
    brother: 'Brother',
    sister: 'Sister',
    husband: 'Husband',
    wife: 'Wife',
    grandfather: 'Grandfather',
    grandmother: 'Grandmother',
    grandson: 'Grandson',
    granddaughter: 'Granddaughter',
    uncle: 'Uncle',
    aunt: 'Aunt',
    nephew: 'Nephew',
    niece: 'Niece',
    cousin: 'Cousin',
    fatherInLaw: 'Father-in-law',
    motherInLaw: 'Mother-in-law',
    sonInLaw: 'Son-in-law',
    daughterInLaw: 'Daughter-in-law',
    brotherInLaw: 'Brother-in-law',
    sisterInLaw: 'Sister-in-law',
    stepFather: 'Step-father',
    stepMother: 'Step-mother',
    stepSon: 'Step-son',
    stepDaughter: 'Step-daughter',
    stepBrother: 'Step-brother',
    stepSister: 'Step-sister',
    greatGrandfather: 'Great-grandfather',
    greatGrandmother: 'Great-grandmother',
    greatGrandson: 'Great-grandson',
    greatGranddaughter: 'Great-granddaughter',
    relative: 'Relative',
    familyMember: 'Family Member',
    ancestor: 'Ancestor',
    descendant: 'Descendant',
    relationshipTo: 'Relationship',
    isMy: 'is my',
    of: 'of',
    sameGeneration: 'Same Generation',
    olderGeneration: 'Older Generation',
    youngerGeneration: 'Younger Generation',
    generationGap: 'Generation Gap',
    self: 'Self',
    unknown: 'Unknown',
    deceased: 'Deceased',
    adopted: 'Adopted',
    foster: 'Foster',
  },
  addParents: 'Add Parents',
  addSpouse: 'Add Spouse',
  addChild: 'Add Child',
  addSibling: 'Add Sibling',
  edit: 'Edit',
  delete: 'Delete',
  name: 'Name',
  gender: 'Gender',
  age: 'Age',
  male: 'Male',
  female: 'Female',
  selectExistingMember: 'Select Existing Member',
  addNewMember: 'Add New Member',
  selectPersonToSeeRelationship: 'Select a person to see relationship',
  noRelationshipFound: 'No relationship found',
  relationshipCalculated: 'Relationship calculated',
}; 